services:
  db:
    image: mariadb:11.4
    container_name: jamithmdev_db
    restart: unless-stopped
    environment:
      MARIADB_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
      MARIADB_DATABASE: ${DB_NAME}
      MARIADB_USER: ${DB_USER}
      MARIADB_PASSWORD: ${DB_PASSWORD}
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - caddy_net

  wordpress:
    image: wordpress:latest
    container_name: jamithmdev_wp
    restart: unless-stopped
    depends_on:
      - db
    environment:
      WORDPRESS_DB_HOST: jamithmdev_db:3306
      WORDPRESS_DB_USER: ${DB_USER}
      WORDPRESS_DB_PASSWORD: ${DB_PASSWORD}
      WORDPRESS_DB_NAME: ${DB_NAME}
    volumes:
      - ./:/var/www/html
      - ./.env:/var/www/html/.env
    networks:
      - caddy_net

  phpmyadmin:
    image: phpmyadmin:latest
    container_name: jamithmdev_pma
    restart: unless-stopped
    depends_on:
      - db
    environment:
      PMA_HOST: jamithmdev_db
      PMA_USER: root
      PMA_PASSWORD: ${DB_ROOT_PASSWORD}
    networks:
      - caddy_net

volumes:
  db_data:

networks:
  caddy_net:
    external: true